### ISSUE TITLE
Instructions on homepage for configuring project don't seem to work

### ISSUE THREAD

**Issue by TomHammersley** [NVIDIA-RTX/NRD#9]
Hi there,

I've just downloaded this denoiser and I'm keen to get it going. I thought I'd start off with building a sample and figuring out how it's all put together.

I tried following the instructions on the home page. My machine has the correct Windows 10 version and the latest SDk. I tried to run 1-Deploy.bat (not deploy.bat as it says on the page), and I get the following errors:
Traceback (most recent call last):
  File "C:\packman-repo\packman-common\6.8.1\packman.py", line 58, in <module>
    import link as linkmodule
  File "C:\packman-repo\packman-common\6.8.1\link.py", line 17, in <module>
    from packman import CONSOLE_ENCODING
  File "C:\packman-repo\packman-common\6.8.1\packman.py", line 2184, in <module>
    read_configuration()
  File "C:\packman-repo\packman-common\6.8.1\packman.py", line 1537, in read_configuration
    configs.append(parser.parse_file(file_path))
  File "C:\packman-repo\packman-common\6.8.1\xmlparser.py", line 194, in parse_file
    root = self._parse_file(filename)
  File "C:\packman-repo\packman-common\6.8.1\xmlparser.py", line 225, in _parse_file
    p.ParseFile(fileobject)
  File "c:\_work\16\s\modules\pyexpat.c", line 471, in EndElement
  File "C:\packman-repo\packman-common\6.8.1\xmlparser.py", line 167, in end_element
    element.end_handler(self)
  File "C:\packman-repo\packman-common\6.8.1\schemaparser.py", line 878, in end_handler
    ConfigElement.REMOTES,
  File "C:\packman-repo\packman-common\6.8.1\xmlparser.py", line 99, in raise_error
    raise PackmanError(self._create_log_message(msg, *args))
errors.PackmanError: C:\Users\tom.hammersley\source\repos\RayTracingDenoiser\ProjectBase\Packman\bootstrap\..\config.packman.xml(line 3): Remote named 's3' is listed in attribute 'remotes' to but not defined!

Is there something else I need to do, configure or define?

Thanks.

**Comment by dzhdanNV** [comment]
Yes, it's a new (but already known) issue. I will upload a fix in a few days.

**Comment by TomHammersley** [comment]
thanks

**Comment by dzhdanNV** [comment]
I updated NRD to v1.8.13. The deployment should work. I have no time to update README.md right now due to other tasks. I will try to do that in a few days. I would be glad if you closed this issue (if deployment works for you) and filed a separate one for mismatched documentation (if needed).

**Comment by TomHammersley** [comment]
This works now, thanks!

**Comment by dzhdanNV** [comment]
@TomHammersley I updated NRD to v1.9.0. Now README.md contains more relevant information (of course, there is still room for improvements)
